steps:
  # ビルドステップ1: テストの実行
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install -g pnpm
        pnpm install
        pnpm test

  # ビルドステップ2: Dockerイメージのビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/discord-reblog/discord-reblog:${SHORT_SHA}', '.']

  # ビルドステップ3: Dockerイメージのプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/discord-reblog/discord-reblog:${SHORT_SHA}']

  # ビルドステップ4: latestタグの設定
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/discord-reblog/discord-reblog:${SHORT_SHA}', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/discord-reblog/discord-reblog:latest']

  # ビルドステップ5: latestタグのプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/discord-reblog/discord-reblog:latest']

  # ビルドステップ6: Cloud Runへのデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'discord-reblog'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/discord-reblog/discord-reblog:${SHORT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'

# 代替変数の設定
substitutions:
  _REGION: asia-northeast1

# イメージの保存
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/discord-reblog/discord-reblog:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/discord-reblog/discord-reblog:latest'

# タイムアウト設定
timeout: 1800s
